### ISSUE TITLE
Save kintone account securely

### ISSUE THREAD

**Issue by the-red** [goqoo-on-kintone/ginue#5]
現在ginuercにアカウント・パスワードを保存はできるが、
そのままベタ書きする必要があるのでかなり危ない。
自分ではここには書かないようにしているw

暗号化して安全に保管できる方法を考えたい。
base64エンコード状態で保管してもセキュリティ上は無意味。
もっと安全で、かつ必要な時はスムーズに複合化できる方法を検討。

**Comment by tkawa** [comment]
netrc というしくみがあって、gitやherokuのcliが利用しています。
これとGPGを組み合わせると暗号化できます。
https://qiita.com/r-tamura/items/c6e49a3eb7f7f8aafb9d

netrc の読み書きですが、heroku cliでも使っている netrc-parser を使えばできそう。
https://github.com/jdxcode/node-netrc-parser

**Comment by the-red** [comment]
おー素晴らしい！！！こういうのが知りたかったんです！
情報ありがとうございます〜。

Windowsでも問題なく動くか心配ではありますが、
Nodeツールなのでおそらく大丈夫ですよね。
試してみます！

**Comment by the-red** [comment]
こちら、`2.0.0-rc2`で実装しました！
`ginue@next`でお試しください〜。

ホームディレクトリ配下に`.netrc`または`.netrc.gpg`が置いてあれば、
それを読み取ってginueの認証に使ってくれます。
セキュリティ上、gpgを強くお勧めします。

REDMEが書けてなくて申し訳ない。。仕様はひとまずコードを読んでいただければ。。
