### ISSUE TITLE
About setup

### ISSUE THREAD

**Issue by m-ando-japan** [goqoo-on-kintone/ginue#9]
README.md に記載のセットアップ方法ですが、-g オプションをつけたほうが誰しも実行できるような気がします。

npm install -g ginue
yarn global add ginue

**Comment by the-red** [comment]
広島のダークナイトさん、ありがとうございます！
独り言以外では初Issueです！

個人的にはyarn add —devでプロジェクトごとにインストールして、node_modeles/.binにPATH通す使い方の方が好きなんですけど、-gインストールの方が手っ取り早く試してもらうには良さそうですね。

npm公式でも「CLUツールはグローバルインストール」が推奨みたいですし。
https://yokotakenji.me/log/programming/js/2071/

両方併記しようと思います。
近々対応しますー。

**Comment by m-ando-japan** [comment]
そうなんですよね。
うちの社員も -g は嫌って言ってますけど、結構ツール系はしれっと -g で公式に書いてあるのを見かけます。
